# Generated by Django 6.0.1 on 2026-03-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_github_url_profile_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post_as_group',
            field=models.BooleanField(default=False, verbose_name='¿Puede publicar como grupo?'),
        ),
    ]
