# Generated by Django 6.0.1 on 2026-01-31 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título del Evento')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('location', models.CharField(max_length=255, verbose_name='Lugar')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nombre del Proyecto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='projects/images/', verbose_name='Imagen del Proyecto')),
                ('is_featured', models.BooleanField(default=False, verbose_name='¿Es destacado?')),
                ('lead_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor a cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('abstract', models.TextField(verbose_name='Resumen')),
                ('date_published', models.DateField(verbose_name='Fecha de Publicación')),
                ('pdf_file', models.FileField(upload_to='publications/pdfs/', verbose_name='Archivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Doctor/Autor')),
            ],
        ),
    ]
