# Generated by Django 6.0.1 on 2026-02-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='ai_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='scholar_id_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/', verbose_name='Archivo PDF'),
        ),
    ]
