# Generated by Django 6.0.1 on 2026-02-16 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_ai_image_url_publication_scholar_id_ref_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(help_text='Ej: desde primavera de 2025', max_length=500)),
                ('category', models.CharField(choices=[('phd', 'Estudiante de Doctorado'), ('undergrad', 'Estudiante de Pregrado'), ('alumni', 'Antiguos Alumnos')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
