# Generated by Django 6.0.1 on 2026-02-17 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la materia')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código (ej: IS407)')),
                ('semester', models.CharField(max_length=100, verbose_name='Semestre (ej: Primavera 2025)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace al curso')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
