# Generated by Django 6.0.1 on 2026-02-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_pics/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
