# Generated by Django 6.0.1 on 2026-02-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_news_image_alter_news_is_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo (Scholar)'),
        ),
    ]
