# Generated by Django 6.0.1 on 2026-03-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='journal_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Revista/Editorial'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='external_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Externo (Directo o Scholar)'),
        ),
    ]
