# Generated by Django 6.0.1 on 2026-03-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_publication_journal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/'),
        ),
    ]
