# Generated by Django 6.0.1 on 2026-03-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_group_announcement',
            field=models.BooleanField(default=False, verbose_name='¿Es comunicado del grupo?'),
        ),
    ]
