# Generated by Django 6.0.1 on 2026-03-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_news_is_group_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors_list',
            field=models.TextField(blank=True, null=True, verbose_name='Autores del artículo'),
        ),
        migrations.AddField(
            model_name='publication',
            name='citations',
            field=models.IntegerField(default=0, verbose_name='Citas'),
        ),
    ]
